language: java
jdk:
  - openjdk11

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# 권한 부여
before_install:
  - chmod +x gradlew
  
beford_deploy:
  - zip -r Springboot_bookstore *
  - mkdir -p deploy
  - mv Springboot_bookstore.zip deploy/Springboot_bookstore.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: changyong-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로 설정
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: changyong-springboot-build #S3 버킷
    key: Springboot_bookstore.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: changyong-springboot-webservice # 웹 콘솔에서 등록한 Codeploy 애플리케이션
    deployment_group: changyong-springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notification:
  email:
    recipients:
      - wnckddyd0525@gmail.com
